import test from 'node:test';
import assert from 'node:assert/strict';
import {createTrafficPoller} from '../traffic-poller.mjs';
const lkr={south:34,north:35,west:-81,east:-80},cgc={south:28,north:29,west:-83,east:-82};
function fixture(){let time=100000,id=0;const jobs=new Map(),requests=[],seen=[],errors=[];
 const poller=createTrafficPoller({now:()=>time,schedule:(fn,ms)=>{jobs.set(++id,{fn,at:time+ms});return id;},cancel:id=>jobs.delete(id),fetchTraffic:(query,signal)=>new Promise((resolve,reject)=>requests.push({query,signal,resolve,reject})),onData:(data,at)=>seen.push({data,at}),onReset:()=>seen.push(null),onError:error=>errors.push(error)});
 return {poller,requests,seen,errors,async advance(ms){time+=ms;for(const [id,job] of [...jobs])if(job.at<=time){jobs.delete(id);job.fn();}await new Promise(setImmediate);},respond(index,label,age=0){requests[index].resolve({fetchedAt:new Date(time-age).toISOString(),aircraft:[{id:label}]});}};
}
test('view switch bypasses ten-second poll and aborts the abandoned request',async()=>{const f=fixture();f.poller.sync(cgc);await f.advance(180);assert.equal(f.requests.length,1);f.poller.sync(lkr);assert.equal(f.requests[0].signal.aborted,true);await f.advance(180);assert.deepEqual(f.requests[1].query,lkr);f.respond(1,'LKR');await f.advance(0);f.respond(0,'CGC');await f.advance(0);assert.equal(f.seen.at(-1).data.aircraft[0].id,'LKR');f.poller.stop();});
test('returning to a fit uses its fresh cache immediately then refreshes',async()=>{const f=fixture();f.poller.sync(cgc);await f.advance(180);f.respond(0,'CGC');await f.advance(0);f.poller.sync(lkr);await f.advance(180);f.respond(1,'LKR');await f.advance(0);f.poller.sync(cgc);assert.equal(f.seen.at(-1).data.aircraft[0].id,'CGC');await f.advance(180);assert.equal(f.requests.length,3);f.poller.stop();});
test('rapid pan changes debounce and unchanged redraws do not cancel polling',async()=>{const f=fixture();f.poller.sync(lkr);await f.advance(100);f.poller.sync(cgc);await f.advance(100);assert.equal(f.requests.length,0);f.poller.sync(cgc);await f.advance(80);assert.equal(f.requests.length,1);f.respond(0,'CGC');await f.advance(0);f.poller.sync(cgc);await f.advance(10000);assert.equal(f.requests.length,2);f.poller.stop();});
test('turning off or hiding cancels requests and suppresses late responses',async()=>{const f=fixture();f.poller.sync(lkr);await f.advance(180);f.poller.sync(lkr,false);assert.equal(f.requests[0].signal.aborted,true);f.respond(0,'LKR');await f.advance(20000);assert.equal(f.requests.length,1);assert.equal(f.seen.at(-1),null);});
test('expired cache is never shown as current and errors continue polling',async()=>{const f=fixture();f.poller.sync(cgc);await f.advance(180);f.respond(0,'CGC');await f.advance(0);f.poller.sync(lkr);await f.advance(46000);f.poller.sync(cgc);assert.equal(f.seen.at(-1),null);await f.advance(180);f.requests.at(-1).reject(Error('429'));await f.advance(0);assert.equal(f.errors.length,1);const count=f.requests.length;await f.advance(10000);assert.equal(f.requests.length,count+1);f.poller.stop();});
