import test from 'node:test';
import assert from 'node:assert/strict';
import {createBrowserTrafficFetch,trafficPoint} from '../traffic-fetch.mjs';
import {parseTrafficPayload as browserParse} from '../traffic-filter.mjs';
import {parseTrafficPayload as cloudParse} from '../../../traffic-service/worker.mjs';
const epoch=1790966000000,query={south:34,north:35,west:-81,east:-80},raw=time=>({now:time,ac:[{flight:'N12345',lat:34.7,lon:-80.9,gs:100,alt_baro:3000,seen_pos:1}]}),signal=()=>new AbortController().signal;
function setup(callback){let time=epoch;const calls=[],waits=[];return {calls,waits,advance:ms=>time+=ms,fetch:createBrowserTrafficFetch({serviceBase:'https://cloud.example',now:()=>time,wait:async ms=>{waits.push(ms);time+=ms;},fetcher:async(url,options)=>{calls.push({url:String(url),options});return callback(String(url),time);}})};}
test('browser parses original traffic filters identically to the cloud',()=>{const data={ac:[...raw(epoch).ac,{flight:'N2177F',lat:34,lon:-81,gs:200,alt_baro:20000,seen_pos:1},{flight:'OLD',lat:34,lon:-81,gs:100,alt_baro:3000,seen_pos:50}]};assert.deepEqual(browserParse(data,'time'),cloudParse(data,'time'));});
test('browser proxy returns current aircraft without requesting the cloud',async()=>{const f=setup((_url,time)=>new Response('Title:\nMarkdown Content:\n'+JSON.stringify(raw(time))));const d=await f.fetch(query,signal());assert.equal(d.aircraft.length,1);assert.equal(f.calls.length,1);assert.match(f.calls[0].url,/r\.jina\.ai\/https:\/\/opendata\.adsb\.fi\/api\/v3/);await f.fetch(query,signal());assert.equal(f.waits[1],3500);});
test('429 cools down browser proxy while retaining cloud fallback',async()=>{const f=setup((url,time)=>url.startsWith('https://r.jina.ai')?new Response('',{status:429,headers:{'retry-after':'60'}}):Response.json({aircraft:[],fetchedAt:new Date(time).toISOString()}));await f.fetch(query,signal());await f.fetch(query,signal());assert.equal(f.calls.filter(c=>c.url.startsWith('https://r.jina.ai')).length,1);f.advance(60001);await f.fetch(query,signal());assert.equal(f.calls.filter(c=>c.url.startsWith('https://r.jina.ai')).length,2);});
test('stale proxy data uses cloud rather than masquerading as fresh traffic',async()=>{const f=setup(url=>url.startsWith('https://r.jina.ai')?new Response(JSON.stringify(raw(epoch-60000))):Response.json({aircraft:[],fetchedAt:new Date(epoch).toISOString()}));assert.deepEqual((await f.fetch(query,signal())).aircraft,[]);assert.equal(f.calls.length,2);});
test('cancelling abandoned view does not request another feed',async()=>{const controller=new AbortController();controller.abort();const f=setup(()=>{throw Error('should not fetch');});await assert.rejects(f.fetch(query,controller.signal));assert.equal(f.calls.length,0);});
test('point query keeps bounded radius and existing geographic quantization',()=>{assert.deepEqual(trafficPoint(query),{lat:'34.5',lon:'-80.5',radius:40});assert.equal(trafficPoint({south:0,north:30,west:0,east:30}).radius,250);});
