import {CATEGORIES,COLORS,statusOf,observationTime,observationUsable,selectLatest,ceiling,conditions,conditionMetricClass,wind,compactWind,windDisplayLevel,shouldDisplayWind,interpolateWind,fuelPriceClass,fuelPriceVisible,hasRainOrMist,hasFog,hasThunderstorm,intersectsBounds,containsPoint,containsPointOrNearLine,gairmetExpiresAt,tfrIsVisible,tfrIsActive,fixedAirportLabelChoice} from './weather.mjs?v=20260920-klkr-label1';
import {filterFeatureGroups,makeRegionFilter} from './region-filter.mjs?v=20260920-state-filter1';
import {alwaysVisibleTrafficIdentifiers,radarCoverageWithinArea,trafficAreas,trafficButtonDetail,trafficCircleEnabled,trafficDataFresh,trafficHasConstantLabel,trafficIconKind,trafficPollingNeeded,trafficVisibleAtZoom,trafficWithinArea} from './traffic-display.mjs?v=20260921-live-traffic-only1';
import {anchoredPan,pinchView} from './map-navigation.mjs?v=20260920-map-gesture1';
import {frontGlyphs,frontNames,frontProximityText} from './front-display.mjs?v=20260923-front-symbols1';
const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg';
window.METAR_STARTED=true;
const defaultPan=[48,30];
const ALOFT_FRAME_INTERVAL=32,ALOFT_VECTOR_INTERVAL=200;
const map=$('map');let aloftCanvas=$('winds-aloft-canvas'),aloftContext=null,aloftWorker=null;const trafficCanvas=$('traffic-canvas'),trafficContext=trafficCanvas.getContext('2d',{alpha:true});let stations=[],states=[],airspaces=[],airmets=[],sigmets=[],tfrs=[],waterData={rivers:[],lakes:[]},waterDetailData={rivers:[],lakes:[],overviewRivers:[],overviewLakes:[],t73Rivers:[],t73Lakes:[]},waterLoaded=false,waterLoading=false,waterDetailLoaded=false,waterDetailLoading=false,reports=new Map(),selected=null,width=0,height=0,baseScale=1,mapCenterY=0,zoom=1,pan=[...defaultPan],scFitView=true,feed=null,loading=false,timer,radarOn=true,aloftOn=true,lightningOn=false,windOn=true,trafficOn=true,trafficLoading=false,trafficTimer=null,trafficAircraft=[],trafficScreen=[],trafficSelected=null,trafficFetchedAt=0,airmetOn=false,sigmetOn=true,hazardsLoaded=false,hazardsLoading=false,tfrsLoaded=false,tfrsLoading=false,displayedIds=new Set(),aloftPayload=null,aloftLevel='3000',aloftData=null,aloftLookup=new Map(),aloftLoading=false,aloftParticles=[],aloftAnimation=null,aloftLastFrame=0,aloftPointerQuietUntil=0,trafficRadarCoverage=new Map(),trafficRadarSource=null;
const nodes=new Map();let establishedRegion=null;
let frontsOn=true,frontsData=null,frontsLoading=false;
const radarBounds={west:-91,east:-75,south:24,north:40};
const terrainBounds={west:-91,east:-75,south:24,north:40};
const scFloridaView={west:-83.7,east:-79,south:27.45,north:35.46};
const scFloridaAirports=new Set(['KSAV','KAYS','KRVJ','KVDI','KSSI','KBQK']);
const featuredFuelAirports=new Set(['KLKR','K35A','KAFP','KCDN','KCUB','KCGC','KHVS','KINF','KRCZ','KX60','KPYG','X35','KCTY']);
const serviceBase='https://bell-family-metar.rbell.workers.dev';
const zoomOnlyAirports=new Map([['SC00',1],['T73',1.5],['28A',1.5],['N52',1.5],['SC76',1.5],['07NC',2],['2NC1',2.4],['NC21',2.4],['55SC',2.4],['39SC',2.4],['01SC',2.4]]);
const catawbaWatereeRivers=new Set(['Catawba River','Wateree River']);
const selectedDetailedRivers=new Set(['Catawba River','Wateree River','Fishing Creek','Lynches River','Little Lynches River','Rocky Creek','Cedar Creek','Big Wateree Creek']);
const catawbaWatereeLakes=new Set(['Lake Norman','Mountain Island Lake','Lake Wylie','Lookout Shoals Lake','Lake Hickory','Fishing Creek Lake','Fishing Creek Reservoir','Great Falls Reservoir','Cedar Creek Reservoir','Wateree Lake']);
const merc=lat=>Math.log(Math.tan(Math.PI/4+lat*Math.PI/360))*180/Math.PI;
const unmerc=value=>(Math.atan(Math.exp(value*Math.PI/180))-Math.PI/4)*360/Math.PI;
// Keep the user-selected regional view stable as airports are added or removed.
const fixedView={west:-83.36,east:-78.07223,south:32.03,north:35.43179};
const center=[(fixedView.west+fixedView.east)/2,(merc(fixedView.south)+merc(fixedView.north))/2];
const extent=[fixedView.east-fixedView.west,merc(fixedView.north)-merc(fixedView.south)];
function useMainThreadAloft(){
 aloftWorker?.terminate();aloftWorker=null;const replacement=aloftCanvas.cloneNode(false);aloftCanvas.replaceWith(replacement);aloftCanvas=replacement;aloftContext=aloftCanvas.getContext('2d',{alpha:true});if(width&&height){aloftCanvas.width=width;aloftCanvas.height=height;}startAloftAnimation();
}
function initializeAloftRenderer(){
 if(typeof Worker!=='function'||typeof aloftCanvas.transferControlToOffscreen!=='function'){aloftContext=aloftCanvas.getContext('2d',{alpha:true});return;}
 try{aloftWorker=new Worker(new URL('./wind-worker.js?v=20260920-pi-portable2',import.meta.url));aloftWorker.onerror=()=>useMainThreadAloft();const offscreen=aloftCanvas.transferControlToOffscreen();aloftWorker.postMessage({type:'init',canvas:offscreen},[offscreen]);}catch{useMainThreadAloft();}
}
function syncAloftWorkerView(){if(aloftWorker&&width&&height)aloftWorker.postMessage({type:'view',view:{width,height,center,baseScale,zoom,pan,mapCenterY}});}
initializeAloftRenderer();
function xy(lon,lat){return [(lon-center[0])*baseScale*zoom+width/2+pan[0],(center[1]-merc(lat))*baseScale*zoom+mapCenterY+pan[1]];}
function visibleBounds(padding=0){const west=(-padding-width/2-pan[0])/(baseScale*zoom)+center[0],east=(width+padding-width/2-pan[0])/(baseScale*zoom)+center[0],north=unmerc(center[1]-(-padding-mapCenterY-pan[1])/(baseScale*zoom)),south=unmerc(center[1]-(height+padding-mapCenterY-pan[1])/(baseScale*zoom));return {west:Math.min(west,east),east:Math.max(west,east),south:Math.min(south,north),north:Math.max(south,north)};}
function trafficAge(aircraft){return Math.max(0,Math.round(Number(aircraft.age||0)+(Date.now()-trafficFetchedAt)/1000));}
function trafficAreaVisible(area){const [x,y]=xy(area.lon,area.lat);return x>=0&&x<=width&&y>=0&&y<=height;}
function visibleTrafficAreas(){return trafficAreas.filter(trafficAreaVisible);}
function trafficAreaActive(area){return trafficCircleEnabled({trafficOn,zoom,areaVisible:trafficAreaVisible(area),radarCoverage:trafficRadarCoverage.get(area.id),...area});}
function activeTrafficAreas(){return trafficAreas.filter(trafficAreaActive);}
function updateTrafficModeUi(areas=activeTrafficAreas()){const button=$('traffic-toggle'),ids=areas.map(area=>area.id),mode=ids.length?ids.join('-'):'regional';button.classList.toggle('klkr-area',ids.length>0);if(button.dataset.mode!==mode){button.dataset.mode=mode;const label=document.createElement('span'),detail=document.createElement('small');label.className='traffic-label';label.textContent='GA Traffic';detail.textContent=trafficButtonDetail(ids);button.replaceChildren(label,document.createElement('br'),detail);}button.title=ids.length?`Show GA traffic below 180 knots within 50 statute miles of ${ids.join(' and ')}`:'Show GA traffic below 180 knots at 150% and closer; listed aircraft appear at every zoom';}
function drawTrafficArea(area){const [x,y]=xy(area.lon,area.lat),east=xy(area.lon+area.radiusSm/(69.172*Math.cos(area.lat*Math.PI/180)),area.lat),radius=Math.abs(east[0]-x),label='GA Traffic',areaColor='#be9df680';trafficContext.save();trafficContext.fillStyle='#be9df60a';trafficContext.strokeStyle=areaColor;trafficContext.lineWidth=2.5;trafficContext.setLineDash([9,6]);trafficContext.beginPath();trafficContext.arc(x,y,radius,0,Math.PI*2);trafficContext.fill();trafficContext.stroke();trafficContext.setLineDash([]);trafficContext.font='bold 12px Inter, Segoe UI, sans-serif';const labelWidth=trafficContext.measureText(label).width+12,labelX=x+(area.labelSide==='west'?-.72:.72)*radius-labelWidth/2,labelY=y+radius*.13;trafficContext.fillStyle='#7c3aed';trafficContext.fillRect(labelX,labelY-14,labelWidth,20);trafficContext.fillStyle='#fff';trafficContext.fillText(label,labelX+6,labelY);trafficContext.restore();}
function visibleTraffic(){if(!trafficOn)return [];const bounds=visibleBounds(30),areas=activeTrafficAreas();return trafficAircraft.filter(aircraft=>{const listed=trafficHasConstantLabel(aircraft,alwaysVisibleTrafficIdentifiers),visible=listed||(areas.length?areas.some(area=>trafficWithinArea(aircraft,area)):trafficVisibleAtZoom(aircraft,zoom,alwaysVisibleTrafficIdentifiers));return visible&&aircraft.lon>=bounds.west&&aircraft.lon<=bounds.east&&aircraft.lat>=bounds.south&&aircraft.lat<=bounds.north;}).slice(0,75);}
function positionTrafficTooltip(aircraft,event){const box=$('traffic-tooltip');if(!aircraft){box.hidden=true;return;}box.replaceChildren();const id=document.createElement('b');id.textContent=aircraft.id;const speed=aircraft.speed!==null&&Number.isFinite(Number(aircraft.speed))?`${Math.round(aircraft.speed)} kt`:'Speed unavailable',altitude=aircraft.altitude!==null&&Number.isFinite(Number(aircraft.altitude))?`${Number(aircraft.altitude).toLocaleString()} ft MSL`:'Altitude unavailable';box.append(id,document.createTextNode(`\n${speed}\n${altitude}\n${trafficAge(aircraft)} sec old`));box.hidden=false;const point=xy(aircraft.lon,aircraft.lat),rect=map.getBoundingClientRect(),anchorX=event?.clientX??rect.left+point[0]*rect.width/width,anchorY=event?.clientY??rect.top+point[1]*rect.height/height,tip=box.getBoundingClientRect(),gap=14;box.style.left=`${Math.max(8,Math.min(innerWidth-tip.width-8,anchorX+gap))}px`;box.style.top=`${Math.max(8,Math.min(innerHeight-tip.height-8,anchorY+gap))}px`;}
function drawTrafficIcon(aircraft,selectedAircraft){const kind=trafficIconKind(aircraft,alwaysVisibleTrafficIdentifiers),iconColor=selectedAircraft?'#fff':'#76d9ff';trafficContext.fillStyle=iconColor;trafficContext.strokeStyle='#06131b';trafficContext.lineWidth=1.6;if(kind==='helicopter'){trafficContext.globalAlpha=.55;trafficContext.strokeStyle=iconColor;trafficContext.lineWidth=1;trafficContext.beginPath();trafficContext.arc(0,-1,8,0,Math.PI*2);trafficContext.stroke();trafficContext.globalAlpha=1;trafficContext.strokeStyle='#06131b';trafficContext.lineWidth=1.6;trafficContext.beginPath();trafficContext.ellipse(0,-1,3.8,5.5,0,0,Math.PI*2);trafficContext.fill();trafficContext.stroke();trafficContext.beginPath();trafficContext.moveTo(0,4);trafficContext.lineTo(0,9);trafficContext.moveTo(-2,9);trafficContext.lineTo(2,9);trafficContext.moveTo(0,7);trafficContext.lineTo(0,11);trafficContext.stroke();return;}trafficContext.beginPath();if(kind==='airplane'){trafficContext.moveTo(0,-10);trafficContext.lineTo(2,-2);trafficContext.lineTo(8,2);trafficContext.lineTo(8,4);trafficContext.lineTo(2,3);trafficContext.lineTo(2,8);trafficContext.lineTo(4,10);trafficContext.lineTo(-4,10);trafficContext.lineTo(-2,8);trafficContext.lineTo(-2,3);trafficContext.lineTo(-8,4);trafficContext.lineTo(-8,2);trafficContext.lineTo(-2,-2);}else{trafficContext.moveTo(0,-8);trafficContext.lineTo(5,7);trafficContext.lineTo(0,4);trafficContext.lineTo(-5,7);}trafficContext.closePath();trafficContext.stroke();trafficContext.fill();}
function drawTraffic(){
 trafficContext.clearRect(0,0,width,height);trafficScreen=[];const areas=activeTrafficAreas();updateTrafficModeUi(areas);if(!trafficOn){$('traffic-tooltip').hidden=true;return;}for(const area of areas)drawTrafficArea(area);const aircraftList=visibleTraffic();trafficContext.lineJoin='round';
 for(const aircraft of aircraftList){const [x,y]=xy(aircraft.lon,aircraft.lat),angle=(Number(aircraft.track)||0)*Math.PI/180,selectedAircraft=aircraft.id===trafficSelected;trafficScreen.push({...aircraft,x,y});trafficContext.save();trafficContext.translate(x,y);trafficContext.rotate(angle);drawTrafficIcon(aircraft,selectedAircraft);trafficContext.restore();
  if(trafficHasConstantLabel(aircraft,alwaysVisibleTrafficIdentifiers)){const label=aircraft.id;trafficContext.font='bold 11px Consolas, monospace';const labelWidth=Math.ceil(trafficContext.measureText(label).width)+10,labelHeight=18;let left=x+11;if(left+labelWidth>width-4)left=x-labelWidth-11;const top=Math.max(4,Math.min(height-labelHeight-4,y-labelHeight/2));trafficContext.strokeStyle=selectedAircraft?'#fff':'#76d9ff';trafficContext.lineWidth=1;trafficContext.strokeRect(left+.5,top+.5,labelWidth-1,labelHeight-1);trafficContext.fillStyle='#e7f8ff';trafficContext.fillText(label,left+5,top+13);}
 }
 const selectedAircraft=trafficScreen.find(aircraft=>aircraft.id===trafficSelected);if(trafficSelected&&!selectedAircraft){trafficSelected=null;$('traffic-tooltip').hidden=true;}else if(selectedAircraft&&!$('traffic-tooltip').hidden)positionTrafficTooltip(selectedAircraft);
}
function trafficAtEvent(event){if(!trafficOn)return null;const rect=map.getBoundingClientRect(),x=(event.clientX-rect.left)*width/rect.width,y=(event.clientY-rect.top)*height/rect.height;let best=null,distance=15;for(const aircraft of trafficScreen){const candidate=Math.hypot(x-aircraft.x,y-aircraft.y);if(candidate<distance){best=aircraft;distance=candidate;}}return best;}
function trafficQuery(){const areas=activeTrafficAreas();if(areas.length){const boxes=areas.map(area=>{const latRadius=area.radiusSm/69.172,lonRadius=latRadius/Math.cos(area.lat*Math.PI/180);return {south:area.lat-latRadius,north:area.lat+latRadius,west:area.lon-lonRadius,east:area.lon+lonRadius};});return {south:Math.min(...boxes.map(box=>box.south)),north:Math.max(...boxes.map(box=>box.north)),west:Math.min(...boxes.map(box=>box.west)),east:Math.max(...boxes.map(box=>box.east))};}const bounds=visibleBounds(20);return {south:Math.max(-90,bounds.south),north:Math.min(90,bounds.north),west:Math.max(-180,bounds.west),east:Math.min(180,bounds.east)};}
async function loadTraffic(){
 clearTimeout(trafficTimer);trafficTimer=null;if(!trafficOn||!trafficPollingNeeded(zoom,alwaysVisibleTrafficIdentifiers)||document.hidden||trafficLoading)return;trafficLoading=true;
 try{const query=trafficQuery(),url=new URL(`${serviceBase}/traffic`);for(const [name,value] of Object.entries(query))url.searchParams.set(name,value.toFixed(3));const response=await fetch(url,{cache:'no-store',signal:AbortSignal.timeout(9000)}),data=await response.json();if(!response.ok||!Array.isArray(data.aircraft))throw Error('Traffic unavailable');trafficAircraft=data.aircraft;trafficFetchedAt=Date.parse(data.fetchedAt)||Date.now();$('traffic-toggle').classList.remove('traffic-error');$('traffic-toggle').classList.add('traffic-live');drawTraffic();}
 catch{if(!trafficAircraft.length||!trafficDataFresh(trafficFetchedAt)){const button=$('traffic-toggle');trafficAircraft=[];button.classList.remove('traffic-live');button.classList.add('traffic-error');drawTraffic();button.title='GA traffic is temporarily unavailable';}}
 finally{trafficLoading=false;if(trafficOn&&trafficPollingNeeded(zoom,alwaysVisibleTrafficIdentifiers)&&!document.hidden)trafficTimer=setTimeout(loadTraffic,10000);}
}
function resetAloftParticle(particle){const bounds=visibleBounds(20),west=Math.max(-91,bounds.west),east=Math.min(-75,bounds.east),south=Math.max(24,bounds.south),north=Math.min(40,bounds.north);particle.lon=west+Math.random()*Math.max(.01,east-west);particle.lat=south+Math.random()*Math.max(.01,north-south);particle.age=Math.random()*4;particle.life=4+Math.random()*4;particle.vector=null;particle.vectorUpdateAt=0;}
function prepareAloftParticles(){const count=width<=1100||navigator.deviceMemory&&navigator.deviceMemory<=4?48:80;while(aloftParticles.length>count)aloftParticles.pop();while(aloftParticles.length<count){const particle={};aloftParticles.push(particle);resetAloftParticle(particle);} }
function aloftWindAt(lon,lat){const west=Math.max(-91,Math.min(-75,Math.floor((lon+91)/2)*2-91)),east=Math.min(-75,west+2),south=Math.max(24,Math.min(40,Math.floor((lat-24)/2)*2+24)),north=Math.min(40,south+2),a=aloftLookup.get(`${west},${south}`),b=aloftLookup.get(`${east},${south}`),c=aloftLookup.get(`${west},${north}`),d=aloftLookup.get(`${east},${north}`);if(!a||!b||!c||!d)return interpolateWind(aloftData?.points,lon,lat);const tx=east===west?0:(lon-west)/(east-west),ty=north===south?0:(lat-south)/(north-south),mix=(key)=>(a[key]*(1-tx)+b[key]*tx)*(1-ty)+(c[key]*(1-tx)+d[key]*tx)*ty,u=mix('u'),v=mix('v');return {u,v,speed:Math.hypot(u,v)};}
function animateAloft(timestamp){aloftAnimation=null;if(!aloftOn||!aloftData?.points?.length||document.hidden)return;if(timestamp<aloftPointerQuietUntil||aloftLastFrame&&timestamp-aloftLastFrame<ALOFT_FRAME_INTERVAL){aloftAnimation=requestAnimationFrame(animateAloft);return;}prepareAloftParticles();const dt=Math.min(.06,Math.max(0,(timestamp-(aloftLastFrame||timestamp))/1000));aloftLastFrame=timestamp;const bounds=visibleBounds(35);aloftContext.clearRect(0,0,width,height);aloftContext.lineWidth=1.35;aloftContext.lineCap='round';aloftContext.strokeStyle='#bdefff';
 for(const particle of aloftParticles){if(particle.age>=particle.life||particle.lon<bounds.west||particle.lon>bounds.east||particle.lat<bounds.south||particle.lat>bounds.north)resetAloftParticle(particle);if(timestamp>=particle.vectorUpdateAt){particle.vector=aloftWindAt(particle.lon,particle.lat);particle.vectorUpdateAt=timestamp+ALOFT_VECTOR_INTERVAL;}const vector=particle.vector;if(!vector)continue;const before=xy(particle.lon,particle.lat),rate=.0022;particle.lon+=vector.u*rate*dt/Math.max(.45,Math.cos(particle.lat*Math.PI/180));particle.lat+=vector.v*rate*dt;particle.age+=dt;const after=xy(particle.lon,particle.lat),length=Math.min(18,5+vector.speed*.34),dx=after[0]-before[0],dy=after[1]-before[1],distance=Math.hypot(dx,dy)||1,tailX=after[0]-dx/distance*length,tailY=after[1]-dy/distance*length,fade=Math.min(1,particle.age/.7,(particle.life-particle.age)/.8);aloftContext.globalAlpha=Math.max(0,.18+.5*fade);aloftContext.beginPath();aloftContext.moveTo(tailX,tailY);aloftContext.lineTo(after[0],after[1]);aloftContext.stroke();}
 aloftContext.globalAlpha=1;
 aloftAnimation=requestAnimationFrame(animateAloft);
}
function startAloftAnimation(){if(aloftWorker){aloftWorker.postMessage({type:'enabled',enabled:aloftOn&&!document.hidden});syncAloftWorkerView();return;}if(aloftOn&&aloftData?.points?.length&&!document.hidden&&!aloftAnimation){aloftLastFrame=0;aloftAnimation=requestAnimationFrame(animateAloft);}}
function applyAloftLevel(){const data=aloftPayload?.levels?.[aloftLevel];if(!Array.isArray(data?.points))return false;aloftData=data;aloftLookup=new Map(data.points.map(point=>[`${point.lon},${point.lat}`,point]));if(aloftWorker)aloftWorker.postMessage({type:'data',points:data.points});else aloftParticles.forEach(resetAloftParticle);const label=aloftLevel==='3000'?'3K':'10K',button=$('aloft-toggle');button.textContent=`${label} Wind`;button.title=`Show or hide animated forecast wind near ${label} ft MSL${data.validTime?` · valid ${data.validTime} UTC`:''}`;startAloftAnimation();return true;}
async function loadWindsAloft(force=false){if(aloftLoading||aloftPayload&&!force)return;aloftLoading=true;try{const response=await fetch(`${serviceBase}/winds-aloft`,{cache:'no-store',signal:AbortSignal.timeout(30000)}),data=await response.json();if(!response.ok||!data.levels)throw Error('Winds aloft unavailable');aloftPayload=data;if(!applyAloftLevel())throw Error('Selected winds aloft level unavailable');$('aloft-toggle').classList.remove('radar-error');}catch{$('aloft-toggle').classList.add('radar-error');$('aloft-toggle').title='Winds aloft data is temporarily unavailable';}finally{aloftLoading=false;}}
const isControlled=station=>station.airspaceClasses?.some(value=>['B','C','D'].includes(value));
function significantWeather(station){const report=reports.get(station.id),status=statusOf(report),windLevel=windDisplayLevel(report);return ['IFR','LIFR'].includes(status)||hasRainOrMist(report)||hasFog(report)||hasThunderstorm(report)||windLevel==='wind-yellow'||windLevel==='wind-red';}
function displayStations(){
 const bounds=visibleBounds(90),wide=zoom<.58,candidates=stations.filter(station=>station.lon>=bounds.west&&station.lon<=bounds.east&&station.lat>=bounds.south&&station.lat<=bounds.north&&(!Number.isFinite(station.minZoom)||zoom>=station.minZoom)&&(!wide||isControlled(station)||significantWeather(station)||featuredFuelAirports.has(station.id)||scFloridaAirports.has(station.id)));
 // Weather hazards, the selected airport, KLKR, and the curated SC stations stay visible. The remaining
 // regularly reporting airports are revealed progressively so regional planning
 // views do not turn into a solid block of identifiers and wind barbs.
 candidates.sort((a,b)=>Number(b.base)-Number(a.base)||Number(significantWeather(b))-Number(significantWeather(a))||Number(b.id===selected)-Number(a.id===selected)||Number(b.id==='KLKR')-Number(a.id==='KLKR')||Number(Number.isFinite(b.fuel100LL))-Number(Number.isFinite(a.fuel100LL))||Number(isControlled(b))-Number(isControlled(a))||(a.priority??9)-(b.priority??9)||(b.maxRunway??0)-(a.maxRunway??0)||a.id.localeCompare(b.id));
 if(zoom>=1.75)return candidates;
 const kept=[],points=[],xGap=zoom<.58?74:zoom<1.2?82:62,yGap=zoom<.58?36:zoom<1.2?42:34;
 for(const station of candidates){const point=xy(station.lon,station.lat),zoomThreshold=zoomOnlyAirports.get(station.id),mustShow=station.base&&zoom>=.8||station.id===selected||station.id==='KLKR'||station.id==='KBQK'&&zoom>=1||scFloridaAirports.has(station.id)||featuredFuelAirports.has(station.id)||Number.isFinite(zoomThreshold)&&zoom>=zoomThreshold;if(!mustShow&&points.some(other=>Math.abs(point[0]-other[0])<xGap&&Math.abs(point[1]-other[1])<yGap))continue;kept.push(station);points.push(point);}
 if(scFitView){let extraIndex=0;return kept.filter(station=>station.base||Number.isFinite(zoomOnlyAirports.get(station.id))&&zoom>=zoomOnlyAirports.get(station.id)||extraIndex++%2===0);}
 return kept;
}
function el(tag,attrs={},parent){const e=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));if(parent)parent.append(e);return e;}
function textAt(parent,lon,lat,text,cls){const p=xy(lon,lat),t=el('text',{x:p[0],y:p[1],class:cls},parent);t.textContent=text;}
function geometryPath(geometry){
 const line=coords=>coords.map((c,i)=>`${i?'L':'M'}${xy(...c).map(n=>n.toFixed(2)).join(',')}`).join('');
 if(geometry.type==='Polygon')return geometry.coordinates.map(r=>`${line(r)}Z`).join('');
 if(geometry.type==='MultiPolygon')return geometry.coordinates.map(p=>p.map(r=>`${line(r)}Z`).join('')).join('');
 if(geometry.type==='LineString')return line(geometry.coordinates);
 if(geometry.type==='MultiLineString')return geometry.coordinates.map(line).join('');
 return '';
}
function frontDataCurrent(){const valid=Date.parse(frontsData?.validTime);return Number.isFinite(valid)&&valid<=Date.now()+3600000&&Date.now()-valid<=7*3600000;}
function updateFrontStatus(){const box=$('front-status'),detail=$('front-detail'),available=frontsOn&&frontDataCurrent();box.hidden=!frontsOn;detail.hidden=true;if(!frontsOn)return;if(!available){box.textContent='WPC fronts unavailable or analysis out of date';return;}const time=new Date(frontsData.validTime).toLocaleString([],{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'UTC'}),near=['KLKR','KCGC'].map(id=>{const station=stations.find(item=>item.id===id);return station&&frontProximityText(station,frontsData.fronts);}).filter(Boolean);box.textContent=`WPC surface analysis ${time} UTC${near.length?` · ${near.join(' · ')}`:' · No analyzed front within 75 SM of KLKR or KCGC'} · symbol side illustrative`;if(selected==='KLKR'||selected==='KCGC'){const station=stations.find(item=>item.id===selected),text=station&&frontProximityText(station,frontsData.fronts);if(text){detail.textContent=`${text} (WPC analysis ${time} UTC; movement and passage not determined)`;detail.hidden=false;}}}
function drawFronts(){const layer=$('fronts');layer.replaceChildren();updateFrontStatus();if(!frontsOn||!frontDataCurrent())return;const bounds=visibleBounds(40);for(const front of frontsData.fronts){if(!frontNames[front.type]||!front.coordinates?.length)continue;const coordinates=front.coordinates,lons=coordinates.map(point=>point[0]),lats=coordinates.map(point=>point[1]);if(Math.max(...lons)<bounds.west||Math.min(...lons)>bounds.east||Math.max(...lats)<bounds.south||Math.min(...lats)>bounds.north)continue;const d=geometryPath({type:'LineString',coordinates});if(!d)continue;const frontClass=`front front-${front.type.toLowerCase()}`;el('path',{d,class:frontClass,'aria-label':frontNames[front.type]},layer);if(front.type==='STNRY')el('path',{d,class:'front front-stnry-red','aria-hidden':'true'},layer);const points=coordinates.map(([lon,lat])=>xy(lon,lat)),byColor=new Map();for(const glyph of frontGlyphs(points,front.type,{width,height})){byColor.set(glyph.color,(byColor.get(glyph.color)||'')+glyph.path);}for(const [color,path] of byColor)el('path',{d:path,class:`front-glyph front-glyph-${color}`,'aria-hidden':'true'},layer);}}
async function loadFronts(){if(frontsLoading||!frontsOn||document.hidden)return;frontsLoading=true;try{const response=await fetch(`${serviceBase}/fronts`,{cache:'no-store',signal:AbortSignal.timeout(15000)}),data=await response.json();if(!response.ok||!Array.isArray(data.fronts)||!Number.isFinite(Date.parse(data.validTime)))throw Error('Fronts unavailable');frontsData=data;$('fronts-toggle').classList.remove('fronts-error');}catch{frontsData=null;$('fronts-toggle').classList.add('fronts-error');}finally{frontsLoading=false;drawFronts();}}
function drawHazards(){
 const layer=$('hazards');layer.replaceChildren();
 const bounds=visibleBounds(),now=Date.now(),add=(features,type)=>{for(const f of features){const p=f.properties||{},starts=Date.parse(type==='airmet'?p.validTime:p.validTimeFrom),expires=type==='airmet'?gairmetExpiresAt(p.validTime):Date.parse(p.validTimeTo);if(Number.isFinite(starts)&&starts>now||Number.isFinite(expires)&&expires<=now||!intersectsBounds(f,bounds))continue;const d=geometryPath(f.geometry);if(!d)continue;const hazardClass=String(p.hazard||'hazard').toLowerCase().replace(/[^a-z0-9]+/g,'-');el('path',{d,class:`hazard ${type} hazard-${hazardClass}`,'fill-rule':'evenodd'},layer);}}
 if(airmetOn)add(airmets,'airmet');if(sigmetOn)add(sigmets,'sigmet');
}
function drawTfrs(){
 const layer=$('tfrs');layer.replaceChildren();const bounds=visibleBounds(),now=Date.now();
 for(const feature of tfrs){const properties=feature.properties||{};if(!tfrIsVisible(properties,now)||!intersectsBounds(feature,bounds))continue;const d=geometryPath(feature.geometry);if(!d)continue;const starts=Date.parse(properties.effective),upcoming=Number.isFinite(starts)&&starts>now,active=tfrIsActive(properties,now),stadium=properties.source==='SEAMS';el('path',{d,class:`tfr${upcoming?' upcoming':''}${active?' active':''}${stadium?' seams':''}`,'fill-rule':'evenodd'},layer);}
}
const hazardNames={'IFR':'IFR','TURB-HI':'High-altitude turbulence','TURB-LO':'Low-altitude turbulence','ICE':'Icing','MT_OBSC':'Mountain obscuration','SFC_WND':'Strong surface wind','FZLVL':'Freezing level','M_FZLVL':'Multiple freezing levels','LLWS':'Low-level wind shear','CONVECTIVE':'Convective thunderstorms','TURB':'Turbulence'};
function hazardItemsAt(lon,lat){
 const now=Date.now(),items=[],lineTolerance=12/(baseScale*zoom),add=(feature,type)=>{if(!containsPointOrNearLine(feature,lon,lat,lineTolerance))return;const p=feature.properties||{},starts=Date.parse(type==='airmet'?p.validTime:p.validTimeFrom),expires=type==='airmet'?gairmetExpiresAt(p.validTime):Date.parse(p.validTimeTo);if(Number.isFinite(starts)&&starts>now||Number.isFinite(expires)&&expires<=now)return;items.push({type:type.toUpperCase(),kind:type,id:String(type==='airmet'?(p.product||''):(p.seriesId||'')).trim(),description:hazardNames[p.hazard]||p.hazard||'Hazard',expires});};
 airmets.forEach(feature=>add(feature,'airmet'));sigmets.forEach(feature=>add(feature,'sigmet'));
 for(const feature of airspaces){if(feature.properties?.class!=='R'||!containsPointOrNearLine(feature,lon,lat,lineTolerance))continue;const p=feature.properties||{};items.push({type:'RESTRICTED',kind:'restricted',id:p.id||p.name||'',description:'Restricted area',altitudes:[`${p.lower||'Unavailable'} – ${p.upper||'Unavailable'}`],schedule:p.timesOfUse||''});}
 for(const feature of tfrs){if(!containsPointOrNearLine(feature,lon,lat,lineTolerance))continue;const p=feature.properties||{},starts=Date.parse(p.effective),expires=Date.parse(p.expires);if(!tfrIsVisible(p,now))continue;const stadium=p.source==='SEAMS';items.push({type:stadium?'STADIUM TFR':'TFR',kind:stadium?'seams':'tfr',id:stadium?(p.league||'SEAMS'):(p.notamId||''),description:stadium?[p.title,p.venue].filter(Boolean).join(' · '):(p.title||p.type||'Temporary flight restriction'),subtype:p.type||'',altitudes:Array.isArray(p.altitudes)?p.altitudes:[],starts,expires});}
 const seen=new Set();return items.filter(item=>{const key=`${item.type}|${item.id}|${item.description}|${item.altitudes?.join('|')||''}|${item.expires}`;if(seen.has(key))return false;seen.add(key);return true;}).sort((a,b)=>a.type.localeCompare(b.type)||(a.expires||Infinity)-(b.expires||Infinity));
}
const utc=value=>Number.isFinite(value)?new Date(value).toLocaleString([],{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'UTC',hour12:false})+' UTC':'Unavailable';
function updateHazardTooltip(event){
 const box=$('hazard-tooltip');if(drag){box.hidden=true;return;}const airportId=event.target.closest?.('.airport')?.dataset.airport,station=airportId&&stations.find(item=>item.id===airportId),rect=map.getBoundingClientRect(),px=(event.clientX-rect.left)*width/rect.width,py=(event.clientY-rect.top)*height/rect.height,lon=station?.lon??(px-width/2-pan[0])/(baseScale*zoom)+center[0],lat=station?.lat??unmerc(center[1]-(py-mapCenterY-pan[1])/(baseScale*zoom)),items=hazardItemsAt(lon,lat);if(!items.length){box.hidden=true;return;}
 box.replaceChildren();for(const item of items){const row=document.createElement('div');row.className=item.kind;const name=document.createElement('b'),detail=document.createElement('span'),lines=[];name.textContent=`${item.type}${item.id?` ${item.id}`:''}`;lines.push(item.description);if(item.subtype&&item.subtype!==item.description)lines.push(item.subtype);if(item.altitudes?.length)lines.push(`Altitude: ${item.altitudes.join('; ')}`);if(['tfr','seams'].includes(item.kind)){lines.push(`${Number.isFinite(item.starts)&&item.starts>Date.now()?'Begins':'Effective'} ${utc(item.starts)}`);lines.push(`Expires ${utc(item.expires)}`);}else if(item.schedule)lines.push(`Hours: ${item.schedule}`);else if(['airmet','sigmet'].includes(item.kind))lines.push(Number.isFinite(item.expires)?`Expires ${utc(item.expires)}`:'Expiration unavailable');detail.textContent=lines.join(' · ');row.append(name,document.createTextNode(' — '),detail);box.append(row);}box.hidden=false;const tip=box.getBoundingClientRect(),gap=14;box.style.left=`${Math.max(8,Math.min(innerWidth-tip.width-8,event.clientX+gap))}px`;box.style.top=`${Math.max(8,Math.min(innerHeight-tip.height-8,event.clientY+gap))}px`;
}
function renderKlkrHazards(){
 const box=$('klkr-hazards'),station=stations.find(s=>s.id==='KLKR'),now=Date.now();box.replaceChildren();if(!station){box.hidden=true;return;}
 const matching=[];
 for(const feature of airmets){const starts=Date.parse(feature.properties?.validTime),expires=gairmetExpiresAt(feature.properties?.validTime);if(starts<=now&&expires>now&&containsPoint(feature,station.lon,station.lat))matching.push({type:'AIRMET',kind:'airmet',description:hazardNames[feature.properties?.hazard]||feature.properties?.hazard||'Hazard',expires});}
 for(const feature of sigmets){const starts=Date.parse(feature.properties?.validTimeFrom),expires=Date.parse(feature.properties?.validTimeTo);if((!Number.isFinite(starts)||starts<=now)&&expires>now&&containsPoint(feature,station.lon,station.lat))matching.push({type:'SIGMET',kind:'sigmet',description:hazardNames[feature.properties?.hazard]||feature.properties?.hazard||'Hazard',expires});}
 const seen=new Set();for(const item of matching.sort((a,b)=>a.expires-b.expires||a.type.localeCompare(b.type))){const key=`${item.type}|${item.description}|${item.expires}`;if(seen.has(key))continue;seen.add(key);const entry=document.createElement('span');entry.className=`klkr-hazard ${item.kind}`;entry.textContent=`KLKR ${item.type} — ${item.description} — expires ${new Date(item.expires).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',timeZone:'UTC',hour12:false})} UTC`;box.append(entry);}
 box.hidden=!box.childElementCount;
}
function updateWindBarb(report,node){
 if(!node.barb)return;
 const speed=Number(report?.wspd),direction=Number(report?.wdir),gust=Number(report?.wgst),hasGust=Number.isFinite(gust);
 node.gustLabel.setAttribute('visibility','hidden');
 if(!Number.isFinite(speed)){node.barb.setAttribute('visibility','hidden');node.barbCalm.setAttribute('visibility','hidden');return;}
 const windLevel=windDisplayLevel(report);
 node.barb.setAttribute('class',`wind-barb ${windLevel}`);
 if(!shouldDisplayWind(report,windOn)){node.barb.setAttribute('visibility','hidden');node.barbCalm.setAttribute('visibility','hidden');return;}
 if(speed<3){node.barb.setAttribute('visibility','hidden');node.barbCalm.setAttribute('visibility','visible');return;}
 node.barbCalm.setAttribute('visibility','hidden');
 if(hasGust){
  let x=22,y=-10;
  if(Number.isFinite(direction)){const radians=direction*Math.PI/180;x=Math.sin(radians)*24+Math.cos(radians)*8;y=-Math.cos(radians)*24+Math.sin(radians)*8+4;}
  node.gustLabel.textContent=`G${Math.round(gust)}`;node.gustLabel.setAttribute('x',x);node.gustLabel.setAttribute('y',y);node.gustLabel.setAttribute('visibility','visible');
 }
 if(!Number.isFinite(direction)){node.barb.setAttribute('visibility','hidden');return;}
 node.barb.setAttribute('visibility','visible');node.barb.setAttribute('transform',`rotate(${direction})`);
 let remaining=Math.round(speed/5)*5,y=-36,d='M0,0L0,-36';
 while(remaining>=50){d+=`M0,${y}L10,${y+5}L0,${y+10}Z`;y+=10;remaining-=50;}
 while(remaining>=10){d+=`M0,${y}L10,${y+5}`;y+=5;remaining-=10;}
 if(remaining>=5)d+=`M0,${y}L6,${y+3}`;
 node.barbPath.setAttribute('d',d);
}
function draw(){
 width=map.clientWidth;height=map.clientHeight;map.setAttribute('viewBox',`0 0 ${width} ${height}`);if(!aloftWorker&&(aloftCanvas.width!==width||aloftCanvas.height!==height)){aloftCanvas.width=width;aloftCanvas.height=height;}const trafficRatio=Math.min(2,devicePixelRatio||1);if(trafficCanvas.width!==Math.round(width*trafficRatio)||trafficCanvas.height!==Math.round(height*trafficRatio)){trafficCanvas.width=Math.round(width*trafficRatio);trafficCanvas.height=Math.round(height*trafficRatio);trafficContext.setTransform(trafficRatio,0,0,trafficRatio,0,0);}
 map.classList.toggle('zoom-300',zoom>=3);
 document.getElementById('zoom-level').textContent=`${Math.round(zoom*100)}%`;
 // Fit SC and its nearby airports while keeping markers clear of the bottom legend.
 mapCenterY=height/2+5;
 baseScale=Math.min((width-110)/extent[0],(height-165)/extent[1]);
 baseScale=Math.max(30,baseScale);
 const radar=$('radar-image'),radarTopLeft=xy(radarBounds.west,radarBounds.north),radarBottomRight=xy(radarBounds.east,radarBounds.south);
 radar.setAttribute('x',radarTopLeft[0]);radar.setAttribute('y',radarTopLeft[1]);radar.setAttribute('width',radarBottomRight[0]-radarTopLeft[0]);radar.setAttribute('height',radarBottomRight[1]-radarTopLeft[1]);
 const terrain=$('terrain-image'),terrainTopLeft=xy(terrainBounds.west,terrainBounds.north),terrainBottomRight=xy(terrainBounds.east,terrainBounds.south);terrain.setAttribute('x',terrainTopLeft[0]);terrain.setAttribute('y',terrainTopLeft[1]);terrain.setAttribute('width',terrainBottomRight[0]-terrainTopLeft[0]);terrain.setAttribute('height',terrainBottomRight[1]-terrainTopLeft[1]);
 for(const image of document.querySelectorAll('.lightning-density-image')){image.setAttribute('x',radarTopLeft[0]);image.setAttribute('y',radarTopLeft[1]);image.setAttribute('width',radarBottomRight[0]-radarTopLeft[0]);image.setAttribute('height',radarBottomRight[1]-radarTopLeft[1]);}
 const geo=$('geography');geo.replaceChildren();
 for(let lon=-88;lon<=-74;lon++){const a=xy(lon,28),b=xy(lon,39);el('path',{d:`M${a}L${b}`,class:'grid'},geo);}
 for(let lat=29;lat<=38;lat++){const a=xy(-88,lat),b=xy(-74,lat);el('path',{d:`M${a}L${b}`,class:'grid'},geo);}
 const landClip=$('land-clip');landClip.replaceChildren();for(const f of states){const polygons=f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates;const d=polygons.map(p=>p.map(r=>r.map((c,i)=>`${i?'L':'M'}${xy(...c).map(n=>n.toFixed(2)).join(',')}`).join('')+'Z').join('')).join('');el('path',{d,class:`state ${f.id==='45'?'sc':''}`,'fill-rule':'evenodd'},geo);el('path',{d,'fill-rule':'evenodd'},landClip);}
 drawWater();
 const airspaceLayer=$('airspaces');airspaceLayer.replaceChildren();const viewBounds=visibleBounds(60);
 // Draw FAA shelves below labels and weather markers. Extremely light fills
 // preserve the airspace footprint without dimming the map beneath it.
 for(const f of airspaces){if(!intersectsBounds(f,viewBounds))continue;const polygons=f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates;const d=polygons.map(p=>p.map(r=>r.map((c,i)=>`${i?'L':'M'}${xy(...c).map(n=>n.toFixed(2)).join(',')}`).join('')+'Z').join('')).join('');el('path',{d,class:`airspace class-${f.properties.class.toLowerCase()}`,'fill-rule':'evenodd'},airspaceLayer);}
 drawFronts();drawTfrs();drawHazards();
 const places=$('places');places.replaceChildren();
 textAt(places,-80.9,35.43,'NORTH CAROLINA','region-label');textAt(places,-83.25,33.05,'GEORGIA','region-label');textAt(places,-78.85,32.36,'Atlantic Ocean','ocean-label');
 // Place labels around each station, leaving marker positions geographically exact.
 const shown=displayStations();displayedIds=new Set(shown.map(s=>s.id));for(const s of stations)nodes.get(s.id).g.style.display=displayedIds.has(s.id)?'':'none';const positions=new Map(shown.map(s=>[s.id,xy(s.lon,s.lat)]));
 const boxes=[];const labelWidth=width>1600?52:46;
 const overlap=(a,b)=>a[0]<b[2]&&a[2]>b[0]&&a[1]<b[3]&&a[3]>b[1];
 for(const s of shown){
  const n=nodes.get(s.id),[x,y]=positions.get(s.id);n.g.setAttribute('transform',`translate(${x},${y})`);
   let best=null,bestScore=Infinity;const report=reports.get(s.id),status=statusOf(report),usableReport=observationUsable(report)?report:null,ifrLike=['IFR','LIFR'].includes(status),alwaysConditions=s.id==='KLKR',showKlkrTag=alwaysConditions&&(zoom>=.8||ifrLike),showConditions=Boolean(usableReport)&&(showKlkrTag||!alwaysConditions&&['MVFR','IFR','LIFR'].includes(status)),showAllConditions=showKlkrTag||ifrLike,conditionData=conditions(usableReport,showAllConditions,alwaysConditions),showVisibility=showConditions&&Boolean(conditionData.visibility),showConditionWind=Boolean(usableReport)&&(showKlkrTag||ifrLike&&zoom>=1.5),conditionWidth=showConditionWind?112:55,hasFuel=fuelLabelVisible(s),infoWidth=Math.max(labelWidth,showConditions?conditionWidth:0,hasFuel?76:0),fuelOffset=hasFuel?13:0;
   const fixedChoice=fixedAirportLabelChoice(s.id,zoom,labelWidth),choices=fixedChoice?[fixedChoice]:[[15,5],[-15-labelWidth,5],[-labelWidth/2,-16],[-labelWidth/2,28],[18,-16],[-18-labelWidth,-16],[18,28],[-18-labelWidth,28],[24,46],[-24-labelWidth,46],[20,-34],[-20-labelWidth,-34]];
  if(!fixedChoice)for(const radius of [50,70,90])for(let step=0;step<12;step++){const angle=step*Math.PI/6,dx=Math.cos(angle)*radius,dy=Math.sin(angle)*radius;choices.push([dx-(dx<0?labelWidth:0),dy+5]);}
   for(const [dx,dy] of choices){const left=dx<0?x+dx+labelWidth-infoWidth-3:x+dx-3,right=dx>=0?x+dx+infoWidth+3:x+dx+labelWidth+3,b=[left,y+dy-13,right,y+dy+fuelOffset+(showConditionWind?42:showConditions?(showVisibility?30:18):hasFuel?18:4)];let score=boxes.reduce((v,p)=>v+(overlap(b,p)?1000:0),0);for(const [id,p] of positions){if(id!==s.id&&overlap(b,[p[0]-10,p[1]-10,p[0]+10,p[1]+10]))score+=500;}score+=Math.abs(dx)*.1+Math.abs(dy)*.15;if(score<bestScore){bestScore=score;best={dx,dy,b};}}
  boxes.push(best.b);n.label.setAttribute('x',best.dx);n.label.setAttribute('y',best.dy);
  for(const line of [n.fuelLabel,n.ceilingLabel,n.visibilityLabel,n.windLabel]){line.setAttribute('x',best.dx<0?best.dx+labelWidth:best.dx);line.setAttribute('text-anchor',best.dx<0?'end':'start');}n.fuelLabel.setAttribute('y',best.dy+14);n.ceilingLabel.setAttribute('y',best.dy+14+fuelOffset);n.visibilityLabel.setAttribute('y',best.dy+26+fuelOffset);n.windLabel.setAttribute('y',best.dy+38+fuelOffset);
  const lx=best.dx>0?best.dx-4:best.dx+labelWidth+4,ly=best.dy-5;
  n.leader.setAttribute('d',`M0,0L${lx},${ly}`);n.leader.style.display=s.id==='KCGC'&&Math.abs(zoom-2)<.15?'none':Math.hypot(lx,ly)>27?'':'none';
  }
 syncAloftWorkerView();drawTraffic();if(trafficOn&&trafficPollingNeeded(zoom,alwaysVisibleTrafficIdentifiers)&&!document.hidden&&!trafficLoading&&!trafficTimer)loadTraffic();
}
function createMarkers(){
 for(const s of stations){const g=el('g',{class:'airport',role:'button',tabindex:'0','data-airport':s.id},$('airports')),titleNode=el('title',{},g);
  const weatherHalo=el('circle',{r:21,class:'weather-halo','aria-hidden':'true'},g);
  const fogHalo=el('circle',{r:25,class:'fog-halo','aria-hidden':'true'},g);
  const lightning=el('path',{d:'M5,-27L-1,-15H5L1,-5L14,-19H8L13,-27Z',class:'lightning','aria-hidden':'true'},g);
  const barb=el('g',{class:'wind-barb','aria-hidden':'true'},g),barbPath=el('path',{},barb),gustLabel=el('text',{class:'gust-label',visibility:'hidden','text-anchor':'middle','aria-hidden':'true'},g);
  const leader=el('path',{class:'leader'},g);const halo=el('circle',{r:17,class:'halo'},g);const ring=el('circle',{r:12,class:'ring'},g);const dot=el('circle',{r:7,class:'dot'},g);el('circle',{r:15,class:'hit'},g);const label=el('text',{},g);label.textContent=s.id;const ceilingLabel=el('text',{class:'conditions',visibility:'hidden','aria-hidden':'true'},g),visibilityLabel=el('text',{class:'conditions',visibility:'hidden','aria-hidden':'true'},g),windLabel=el('text',{class:'conditions',visibility:'hidden','aria-hidden':'true'},g);
  const fuelLabel=el('text',{class:'fuel-price',visibility:'hidden','aria-hidden':'true'},g),barbCalm=el('circle',{r:2,class:'calm-wind','aria-hidden':'true'},g);
  nodes.set(s.id,{g,titleNode,halo,ring,dot,label,fuelLabel,ceilingLabel,visibilityLabel,windLabel,leader,weatherHalo,fogHalo,lightning,barb,barbPath,barbCalm,gustLabel});g.addEventListener('click',()=>select(s.id));g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(s.id);}});
 }
}
function distanceMiles(a,b){const radians=Math.PI/180,latDelta=(b.lat-a.lat)*radians,lonDelta=(b.lon-a.lon)*radians,value=Math.sin(latDelta/2)**2+Math.cos(a.lat*radians)*Math.cos(b.lat*radians)*Math.sin(lonDelta/2)**2;return 3958.8*2*Math.asin(Math.sqrt(value));}
function fuelLabelClass(station){const klkr=stations.find(item=>item.id==='KLKR'),nearKlkr=station.state==='NC'&&klkr&&distanceMiles(station,klkr)<=50,baselineId=station.state==='SC'||nearKlkr?'KLKR':station.state==='FL'?'KCGC':station.state==='GA'?'KVDI':null,baseline=baselineId&&stations.find(item=>item.id===baselineId)?.fuel100LL;return `fuel-price ${fuelPriceClass(station.fuel100LL,baseline)}`;}
function fuelLabelVisible(station){return fuelPriceVisible(station.fuel100LL,zoom,featuredFuelAirports.has(station.id))&&(station.id!=='KCUB'||zoom>1.75);}
function airportHoverText(station,report,status,noMetar){
 const usableReport=observationUsable(report)?report:null,lines=[`${station.id} — ${station.name}`];
 if(noMetar)lines.push('Weather: No METAR reporting');
 else if(!usableReport)lines.push(`Weather: ${status==='STALE'?'Stale observation':'No current report'}`);
 else{const visibility=usableReport.visib!=null?`${usableReport.visib} SM`:'Unavailable',temperature=Number.isFinite(usableReport.temp)?`${Math.round(usableReport.temp*9/5+32)}°F / ${usableReport.temp}°C`:'Unavailable',ceilingText=ceiling(usableReport),ceilingSummary=ceilingText==='No ceiling'?'No ceiling':`Ceiling ${ceilingText}`;lines.push(`Weather: ${status} · Wind ${wind(usableReport)} · Visibility ${visibility} · ${ceilingSummary} · Temp ${temperature}`);}
 lines.push(`Elevation: ${Number.isFinite(station.elevationFt)?`${station.elevationFt.toLocaleString()} ft MSL`:'Unavailable'}`);
 if(Number.isFinite(station.fuel100LL)){const service=station.fuelService?` · ${station.fuelService.replace('-', ' ')}`:'';lines.push(`Fuel: 100LL $${station.fuel100LL.toFixed(2)}/gal${service} · reported ${station.fuelPriceReported||'date unavailable'}`);}else lines.push('Fuel: 100LL price unavailable');
 const runwayText=Array.isArray(station.runways)&&station.runways.length?station.runways.map(runway=>`${runway.id} — ${Number(runway.length).toLocaleString()} ft`).join('; '):Number.isFinite(station.maxRunway)?`Longest runway — ${station.maxRunway.toLocaleString()} ft`:'Unavailable';lines.push(`Runways: ${runwayText}`);
 return lines.join('\n');
}
function updateMarkers(){
 const counts={VFR:0,MVFR:0,IFR:0,LIFR:0,UNKNOWN:0};
 for(const s of stations){const report=reports.get(s.id),usableReport=observationUsable(report)?report:null,status=statusOf(report),n=nodes.get(s.id),fuelOnly=Boolean(s.fuelOnly),noWeather=Boolean(s.noWeather),noMetar=fuelOnly||noWeather;if(displayedIds.has(s.id)&&!noMetar)counts[CATEGORIES.includes(status)?status:'UNKNOWN']++;
  const wetWeather=CATEGORIES.includes(status)&&hasRainOrMist(report);n.weatherHalo.classList.toggle('active',wetWeather);
  const fog=CATEGORIES.includes(status)&&hasFog(report);n.fogHalo.classList.toggle('active',fog);
  const lightning=CATEGORIES.includes(status)&&hasThunderstorm(report);n.lightning.classList.toggle('active',lightning);
  const alwaysConditions=s.id==='KLKR',showKlkrTag=alwaysConditions&&(zoom>=.8||['IFR','LIFR'].includes(status)),showConditions=Boolean(usableReport)&&(showKlkrTag||!alwaysConditions&&['MVFR','IFR','LIFR'].includes(status)),ifrLike=['IFR','LIFR'].includes(status),showAllConditions=showKlkrTag||ifrLike,showConditionWind=Boolean(usableReport)&&(showKlkrTag||ifrLike&&zoom>=1.5),conditionData=conditions(usableReport,showAllConditions,alwaysConditions);n.fuelLabel.textContent=Number.isFinite(s.fuel100LL)?`100LL $${s.fuel100LL.toFixed(2)}`:s.fuelPriceUnavailable?'100LL N/A':'';n.fuelLabel.setAttribute('class',fuelLabelClass(s));n.fuelLabel.setAttribute('visibility',s.fuelPriceUnavailable&&zoom>=2||fuelLabelVisible(s)?'visible':'hidden');n.ceilingLabel.textContent=conditionData.ceiling;n.ceilingLabel.setAttribute('class',`conditions${ifrLike?` ${conditionMetricClass(usableReport,'ceiling')}`:''}`.trim());n.ceilingLabel.setAttribute('visibility',showConditions?'visible':'hidden');n.visibilityLabel.textContent=conditionData.visibility;n.visibilityLabel.setAttribute('class',`conditions${ifrLike?` ${conditionMetricClass(usableReport,'visibility')}`:''}`.trim());n.visibilityLabel.setAttribute('visibility',showConditions&&conditionData.visibility?'visible':'hidden');
  n.windLabel.textContent=showConditionWind?compactWind(usableReport):'';n.windLabel.setAttribute('visibility',showConditionWind?'visible':'hidden');
  n.g.setAttribute('class',`airport ${fuelOnly?'fuel-only':noWeather?'no-weather':status==='STALE'?'stale unknown':status==='UNKNOWN'?'unknown':''} ${selected===s.id?'selected':''}`);
  const markerColor=noMetar?'#a5b1b8':COLORS[status];n.dot.setAttribute('fill',markerColor);n.halo.setAttribute('fill',markerColor);
 const hoverText=airportHoverText(s,report,status,noMetar);n.titleNode.textContent=hoverText;n.g.setAttribute('aria-label',`${hoverText.replaceAll('\n',', ')}${wetWeather?', rain or mist reported':''}${fog?', fog reported':''}${lightning?', thunderstorm or lightning reported':''}. Show details.`);
  updateWindBarb(usableReport,n);
 }
 Object.entries(counts).forEach(([k,v])=>$(`count-${k}`).textContent=v);
 if(selected)renderDetail();
}
function select(id){selected=id;updateMarkers();$('detail').hidden=false;updateFrontStatus();}
function renderDetail(){
 const s=stations.find(s=>s.id===selected),r=reports.get(selected),usableReport=observationUsable(r)?r:null,status=statusOf(r),time=observationTime(r);
 const fuelOnly=Boolean(s.fuelOnly),noWeather=Boolean(s.noWeather),noMetar=fuelOnly||noWeather;$('airport-id').textContent=s.id;$('airport-name').textContent=s.name;$('category').textContent=noMetar?'NO METAR':status==='UNKNOWN'?'NO DATA':status;$('category').style.color=noMetar?'#a5b1b8':COLORS[status];
 $('observation-age').textContent=noMetar?'This airport does not publish METAR observations.':Number.isFinite(time)?`Observed ${new Date(time).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',timeZone:'UTC',hour12:false})} UTC · ${Math.max(0,Math.round((Date.now()-time)/60000))} min ago`:'No recent observation received';
 $('stale-note').hidden=status!=='STALE';$('stale-note').textContent=usableReport?'Older observation. Current conditions may differ.':'Observation is over two hours old. Weather details are hidden.';$('wind').textContent=wind(usableReport);$('visibility').textContent=usableReport?.visib!=null?`${usableReport.visib} SM`:'Unavailable';$('ceiling').textContent=ceiling(usableReport);$('temperature').textContent=Number.isFinite(usableReport?.temp)?`${Math.round(usableReport.temp*9/5+32)}°F / ${usableReport.temp}°C`:'Unavailable';const hasFuel=Number.isFinite(s.fuel100LL)||s.fuelPriceUnavailable,fuelDetail=$('fuel-detail');fuelDetail.hidden=!hasFuel;if(hasFuel){$('fuel-price-detail').textContent=Number.isFinite(s.fuel100LL)?`$${s.fuel100LL.toFixed(2)} / gal`:'Price unavailable';const service=s.fuelService?`${s.fuelService.replace('-', ' ')} · `:'';$('fuel-detail-note').textContent=Number.isFinite(s.fuel100LL)?`${service}reported ${s.fuelPriceReported||'date unavailable'}`:'100LL is listed, but no current posted price was found.';}$('raw').textContent=noMetar?`${s.id} does not publish METAR observations.`:usableReport?.rawOb||(!observationUsable(r)&&r?'Observation is over two hours old and is hidden.':'No METAR is available for this airport.');
}
function notify(message,error=false){$('message').textContent=message;$('message').hidden=!message;$('message').classList.toggle('error',error);}
function updateClock(){
 const now=new Date(),utc=now.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',timeZone:'UTC',hour12:false}),local=now.toLocaleTimeString([],{hour:'numeric',minute:'2-digit',hour12:true});
 $('clock').textContent=`${utc} UTC · ${local} Local`;
 if(feed?.fetchedAt){const mins=Math.max(0,Math.floor((Date.now()-Date.parse(feed.fetchedAt))/60000));$('update-text').textContent=`${feed.error?'Connection lost · last check':'Checked'} ${mins<1?'just now':`${mins} min ago`}`;}
}
function updateRadar(){
 if(!radarOn)return;
 const image=$('radar-image'),bucket=Math.floor(Date.now()/300000);
 image.classList.remove('unavailable');image.setAttribute('href',`${serviceBase}/radar?v=regional1-${bucket}`);
}
async function analyzeTrafficAreaRadar(source){if(!source||source===trafficRadarSource)return;trafficRadarSource=source;const coverage=new Map();try{const response=await fetch(source,{cache:'force-cache',signal:AbortSignal.timeout(25000)});if(!response.ok)throw Error('Radar image unavailable');const bitmap=await createImageBitmap(await response.blob()),canvas=document.createElement('canvas');canvas.width=380;canvas.height=450;const context=canvas.getContext('2d',{willReadFrequently:true});context.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close?.();const pixels=context.getImageData(0,0,canvas.width,canvas.height).data;for(const area of trafficAreas)coverage.set(area.id,radarCoverageWithinArea(pixels,canvas.width,canvas.height,radarBounds,area));}catch(error){console.error(error);}if(source!==trafficRadarSource)return;trafficRadarCoverage=coverage;drawTraffic();}
function updateTerrain(){$('terrain-image').setAttribute('href',`${serviceBase}/terrain?v=mercator2`);}
const keepEstablishedFeature=feature=>!establishedRegion||establishedRegion.touches(feature.geometry);
async function loadWater(){if(waterLoading||waterLoaded)return;waterLoading=true;try{const response=await fetch(`${serviceBase}/water?v=vector1`,{signal:AbortSignal.timeout(35000)}),data=await response.json();if(!response.ok)throw Error('Water layer unavailable');waterData={rivers:(data.rivers||[]).filter(keepEstablishedFeature),lakes:(data.lakes||[]).filter(keepEstablishedFeature)};waterLoaded=true;drawWater();}catch(error){console.error(error);}finally{waterLoading=false;}}
async function loadWaterDetail(){if(waterDetailLoading||waterDetailLoaded)return;waterDetailLoading=true;try{const response=await fetch(`${serviceBase}/water-detail?v=basin11`,{signal:AbortSignal.timeout(130000)}),data=await response.json();if(!response.ok)throw Error('Detailed water layer unavailable');waterDetailData={rivers:(data.rivers||[]).filter(keepEstablishedFeature),lakes:(data.lakes||[]).filter(keepEstablishedFeature),overviewRivers:(data.overviewRivers||[]).filter(keepEstablishedFeature),overviewLakes:(data.overviewLakes||[]).filter(keepEstablishedFeature),t73Rivers:(data.t73Rivers||[]).filter(keepEstablishedFeature),t73Lakes:(data.t73Lakes||[]).filter(keepEstablishedFeature)};waterDetailLoaded=true;drawWater();}catch(error){console.error(error);}finally{waterDetailLoading=false;}}
function drawWater(){const layer=$('water');layer.replaceChildren();if(!waterLoaded)return;const bounds=visibleBounds(30),add=(features,cls)=>{const d=features.filter(feature=>intersectsBounds(feature,bounds)).map(feature=>geometryPath(feature.geometry)).filter(Boolean).join('');if(d)el('path',{d,class:cls,'fill-rule':'evenodd'},layer);};add(waterData.lakes,'water-lake');add(waterData.rivers,'water-river');if(!waterDetailLoaded)loadWaterDetail();const basinRivers=zoom<=1?waterDetailData.overviewRivers:waterDetailData.rivers,basinLakes=zoom<=1?waterDetailData.overviewLakes:waterDetailData.lakes,mainLakes=basinLakes.filter(feature=>catawbaWatereeLakes.has(feature.properties?.gnis_name)),mainRivers=basinRivers.filter(feature=>catawbaWatereeRivers.has(feature.properties?.gnis_name));add(mainLakes,'water-lake water-detail-lake');add(mainRivers,'water-river water-detail-river');if(zoom>=1.5){add(waterDetailData.lakes.filter(feature=>!catawbaWatereeLakes.has(feature.properties?.gnis_name)),'water-lake water-detail-lake');add(waterDetailData.rivers.filter(feature=>!catawbaWatereeRivers.has(feature.properties?.gnis_name)),'water-river water-detail-river');}const localRivers=waterDetailData.t73Rivers.filter(feature=>!selectedDetailedRivers.has(feature.properties?.gnis_name)),localLakes=waterDetailData.t73Lakes;if(zoom>=4){add(localLakes,'water-lake water-detail-lake');add(localRivers,'water-river water-detail-river');}else if(zoom>=3){add(localLakes.filter(feature=>feature.properties?.gnis_name==='Lancaster Reservoir'),'water-lake water-detail-lake');add(localRivers.filter(feature=>Number(feature.properties?.streamorde)>=5),'water-river water-detail-river');}}
function updateLightning(){
 if(!lightningOn)return;
 const bucket=Math.floor(Date.now()/300000);for(const image of document.querySelectorAll('.lightning-density-image')){image.classList.remove('unavailable');image.setAttribute('href',`${serviceBase}/lightning?frame=${image.dataset.frame}&v=regional1-${bucket}`);}
}
async function loadHazards(force=false,silent=false){
 if(hazardsLoading||hazardsLoaded&&!force)return;hazardsLoading=true;
 try{const r=await fetch(`${serviceBase}/hazards`,{cache:'no-store',signal:AbortSignal.timeout(23000)}),data=await r.json();if(!r.ok)throw Error('Hazard service unavailable');airmets=data.airmets?.features||[];sigmets=data.sigmets?.features||[];hazardsLoaded=true;$('airmet-toggle').classList.remove('hazard-error');$('sigmet-toggle').classList.remove('hazard-error');renderKlkrHazards();draw();}
 catch{$('airmet-toggle').classList.add('hazard-error');$('sigmet-toggle').classList.add('hazard-error');if(!silent)notify('AIRMET and SIGMET overlays are temporarily unavailable.',true);}
 finally{hazardsLoading=false;}
}
async function loadTfrs(force=false,silent=false){
 if(tfrsLoading||tfrsLoaded&&!force)return;tfrsLoading=true;
 try{const r=await fetch(`${serviceBase}/tfrs?v=2`,{cache:'no-store',signal:AbortSignal.timeout(30000)}),data=await r.json();if(!r.ok)throw Error('TFR service unavailable');tfrs=(data.features||[]).filter(keepEstablishedFeature);tfrsLoaded=true;draw();}
 catch{if(!silent)notify('TFR overlays are temporarily unavailable.',true);}
 finally{tfrsLoading=false;}
}
async function toggleHazard(type){const isAirmet=type==='airmet';if(isAirmet)airmetOn=!airmetOn;else sigmetOn=!sigmetOn;const on=isAirmet?airmetOn:sigmetOn,button=$(isAirmet?'airmet-toggle':'sigmet-toggle');button.classList.toggle('active',on);button.setAttribute('aria-pressed',String(on));if(on)await loadHazards();drawHazards();}
async function refresh(){
 if(loading)return;loading=true;$('refresh').disabled=true;clearTimeout(timer);
 try{const ids=stations.map(s=>s.id),batches=[];for(let index=0;index<ids.length;index+=100)batches.push(ids.slice(index,index+100));const responses=await Promise.all(batches.map(async batch=>{const weatherUrl=new URL(`${serviceBase}/weather`);weatherUrl.searchParams.set('ids',batch.join(','));const response=await fetch(weatherUrl,{cache:'no-store',signal:AbortSignal.timeout(23000)});if(!response.ok)throw Error('Weather connection unavailable');const data=await response.json();if(!Array.isArray(data))throw Error('Unexpected weather response');return data;}));feed={fetchedAt:new Date().toISOString(),reports:selectLatest(responses.flat(),ids),nextCheckAt:new Date(Date.now()+300000).toISOString()};
  reports=new Map(feed.reports.map(r=>[r.icaoId,r]));draw();
  notify(!feed.reports.length?'No recent METAR reports returned. Checking again shortly.':'');
  updateMarkers();updateClock();
 }catch{if(feed)feed.error='Connection lost';notify('Weather connection unavailable. Last observations remain visible; retrying shortly.',true);updateClock();}
 finally{loading=false;$('refresh').disabled=false;const next=feed?.nextCheckAt?Date.parse(feed.nextCheckAt)-Date.now():60000;timer=setTimeout(refresh,Math.max(10000,Math.min(300000,next)));}
}
function changeZoom(factor,anchor=[width/2,height/2]){scFitView=false;const nextZoom=Math.max(.16,Math.min(5,zoom*factor));pan=anchoredPan(pan,zoom,nextZoom,anchor,[width/2,mapCenterY]);zoom=nextZoom;draw();updateMarkers();}
function fitBounds(bounds,magnification=1){const targetScale=Math.min((width-110)/(bounds.east-bounds.west),(height-165)/(merc(bounds.north)-merc(bounds.south)))*magnification,midLon=(bounds.west+bounds.east)/2,midY=(merc(bounds.south)+merc(bounds.north))/2;zoom=Math.max(.16,targetScale/baseScale);pan=[-(midLon-center[0])*baseScale*zoom,-(center[1]-midY)*baseScale*zoom];draw();updateMarkers();}
function fitLkr(){const station=stations.find(item=>item.id==='KLKR');if(!station)return;scFitView=false;zoom=3;pan=[width*.4-width/2-(station.lon-center[0])*baseScale*zoom,height*.5-mapCenterY-(center[1]-merc(station.lat))*baseScale*zoom];draw();select('KLKR');}
function fitCgc(){const station=stations.find(item=>item.id==='KCGC');if(!station)return;scFitView=false;zoom=2;pan=[width*.29-width/2-(station.lon-center[0])*baseScale*zoom,height*.42-mapCenterY-(center[1]-merc(station.lat))*baseScale*zoom];draw();select('KCGC');}
$('zoom-in').onclick=()=>changeZoom(1.25);$('zoom-out').onclick=()=>changeZoom(.8);$('reset').onclick=()=>{scFitView=true;zoom=1;pan=[...defaultPan];draw();updateMarkers();};$('fit-region').onclick=()=>{scFitView=false;fitBounds(scFloridaView,1.25);};$('fit-lkr').onclick=fitLkr;$('fit-cgc').onclick=fitCgc;
$('radar-toggle').onclick=()=>{radarOn=!radarOn;const button=$('radar-toggle'),image=$('radar-image');button.classList.toggle('active',radarOn);button.setAttribute('aria-pressed',String(radarOn));image.classList.toggle('off',!radarOn);if(radarOn)updateRadar();};
$('fronts-toggle').onclick=()=>{frontsOn=!frontsOn;const button=$('fronts-toggle');button.classList.toggle('active',frontsOn);button.setAttribute('aria-pressed',String(frontsOn));drawFronts();if(frontsOn&&!frontDataCurrent())loadFronts();};
$('aloft-toggle').onclick=()=>{aloftOn=!aloftOn;const button=$('aloft-toggle');$('aloft-control').classList.toggle('active',aloftOn);button.setAttribute('aria-pressed',String(aloftOn));aloftCanvas.classList.toggle('off',!aloftOn);if(aloftOn){loadWindsAloft();startAloftAnimation();}else if(aloftWorker)aloftWorker.postMessage({type:'enabled',enabled:false});else{aloftContext.clearRect(0,0,width,height);if(aloftAnimation){cancelAnimationFrame(aloftAnimation);aloftAnimation=null;}}};
$('aloft-level').oninput=event=>{aloftLevel=event.target.value==='1'?'10000':'3000';applyAloftLevel();};
$('lightning-toggle').onclick=()=>{lightningOn=!lightningOn;const button=$('lightning-toggle'),layer=$('lightning-density');button.classList.toggle('active',lightningOn);button.setAttribute('aria-pressed',String(lightningOn));layer.classList.toggle('off',!lightningOn);$('lightning-age-key').hidden=!lightningOn;if(lightningOn)updateLightning();};
$('wind-toggle').onclick=()=>{windOn=!windOn;const button=$('wind-toggle');button.classList.toggle('active',windOn);button.setAttribute('aria-pressed',String(windOn));updateMarkers();};
$('traffic-toggle').onclick=()=>{trafficOn=!trafficOn;const button=$('traffic-toggle');button.classList.toggle('active',trafficOn);button.setAttribute('aria-pressed',String(trafficOn));trafficCanvas.classList.toggle('off',!trafficOn);clearTimeout(trafficTimer);trafficTimer=null;if(trafficOn){button.title='Show GA traffic at 150% and closer; listed aircraft appear at every zoom';drawTraffic();loadTraffic();}else{button.classList.remove('traffic-live');trafficSelected=null;trafficAircraft=[];trafficScreen=[];$('traffic-tooltip').hidden=true;trafficContext.clearRect(0,0,width,height);}};
$('airmet-toggle').onclick=()=>toggleHazard('airmet');$('sigmet-toggle').onclick=()=>toggleHazard('sigmet');
$('radar-image').addEventListener('load',event=>{event.currentTarget.classList.remove('unavailable');$('radar-toggle').classList.remove('radar-error');$('radar-toggle').title='Show or hide NOAA weather radar';analyzeTrafficAreaRadar(event.currentTarget.getAttribute('href'));});
$('radar-image').addEventListener('error',()=>{trafficRadarCoverage=new Map();drawTraffic();$('radar-image').classList.add('unavailable');$('radar-toggle').classList.add('radar-error');$('radar-toggle').title='Radar is temporarily unavailable';});
$('terrain-image').addEventListener('load',()=>{$('terrain-image').classList.remove('unavailable');});
$('terrain-image').addEventListener('error',()=>{$('terrain-image').classList.add('unavailable');});
for(const image of document.querySelectorAll('.lightning-density-image')){image.addEventListener('load',()=>{image.classList.remove('unavailable');$('lightning-toggle').classList.remove('radar-error');$('lightning-toggle').title='Show or hide NOAA lightning strike density from the last hour';});image.addEventListener('error',()=>{image.classList.add('unavailable');$('lightning-toggle').classList.add('radar-error');$('lightning-toggle').title='Lightning data is temporarily unavailable';});}
$('close-detail').onclick=()=>{const previous=selected;selected=null;$('detail').hidden=true;updateMarkers();nodes.get(previous)?.g.focus();};
$('refresh').onclick=refresh;
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{notify('Use F11 in your browser for full screen.');}}
$('fullscreen').onclick=fullscreen;document.addEventListener('fullscreenchange',()=>{$('fullscreen').textContent=document.fullscreenElement?'Exit full screen':'Full screen';});
document.addEventListener('keydown',e=>{if(e.ctrlKey||e.altKey||e.metaKey)return;if(e.key.toLowerCase()==='f')fullscreen();if(e.key==='+'||e.key==='=')changeZoom(1.25);if(e.key==='-')changeZoom(.8);if(e.key==='Home'){e.preventDefault();$('reset').click();}if(e.key==='Escape'&&selected)$('close-detail').click();});
let drag=null,pinch=null;const activePointers=new Map();
function mapPoint(event){const rect=map.getBoundingClientRect();return [event.clientX-rect.left,event.clientY-rect.top];}
function startPinch(){const entries=[...activePointers.entries()].slice(0,2);if(entries.length<2)return;pinch={ids:entries.map(entry=>entry[0]),points:entries.map(entry=>entry[1]),zoom,pan:[...pan]};drag=null;scFitView=false;map.classList.add('dragging');}
map.addEventListener('pointerdown',e=>{const point=mapPoint(e);if(e.target.closest('.airport'))return;activePointers.set(e.pointerId,point);try{map.setPointerCapture(e.pointerId);}catch{}if(activePointers.size>=2){startPinch();return;}const aircraft=trafficAtEvent(e);if(aircraft){trafficSelected=aircraft.id;positionTrafficTooltip(aircraft,e);drawTraffic();return;}trafficSelected=null;$('traffic-tooltip').hidden=true;scFitView=false;drag={pointerId:e.pointerId,x:point[0],y:point[1],pan:[...pan]};map.classList.add('dragging');});
map.addEventListener('pointermove',e=>{if(activePointers.has(e.pointerId))activePointers.set(e.pointerId,mapPoint(e));if(pinch){const points=pinch.ids.map(id=>activePointers.get(id));if(points.every(Boolean)){if(e.pointerType==='touch')e.preventDefault();const view=pinchView(pinch.pan,pinch.zoom,pinch.points,points,[width/2,mapCenterY]);zoom=view.zoom;pan=view.pan;draw();updateMarkers();}return;}if(!drag||drag.pointerId!==e.pointerId)return;const point=mapPoint(e);pan=[drag.pan[0]+point[0]-drag.x,drag.pan[1]+point[1]-drag.y];draw();updateMarkers();});
let hazardTooltipEvent=null,hazardTooltipTimer=null,hazardPointerSample=null,pointerIdleTimer=null;
function hideDormantHover(){pointerIdleTimer=null;hazardTooltipEvent=null;hazardPointerSample=null;if(hazardTooltipTimer){clearTimeout(hazardTooltipTimer);hazardTooltipTimer=null;}$('hazard-tooltip').hidden=true;if(!trafficSelected)$('traffic-tooltip').hidden=true;}
function notePointerActivity(){clearTimeout(pointerIdleTimer);pointerIdleTimer=setTimeout(hideDormantHover,60000);}
map.addEventListener('pointermove',event=>{if(!drag){const aircraft=trafficAtEvent(event);if(aircraft){positionTrafficTooltip(aircraft,event);$('hazard-tooltip').hidden=true;}else if(!trafficSelected)$('traffic-tooltip').hidden=true;}const now=event.timeStamp||performance.now(),previous=hazardPointerSample,elapsed=previous?Math.max(1,now-previous.time):Infinity,speed=previous?Math.hypot(event.clientX-previous.x,event.clientY-previous.y)/elapsed:0;hazardPointerSample={x:event.clientX,y:event.clientY,time:now};hazardTooltipEvent=event;if(hazardTooltipTimer){clearTimeout(hazardTooltipTimer);hazardTooltipTimer=null;}if(speed>.25)$('hazard-tooltip').hidden=true;hazardTooltipTimer=setTimeout(()=>{hazardTooltipTimer=null;if(hazardTooltipEvent&&!trafficAtEvent(hazardTooltipEvent))updateHazardTooltip(hazardTooltipEvent);},180);});
map.addEventListener('pointerleave',()=>{hazardTooltipEvent=null;hazardPointerSample=null;if(hazardTooltipTimer){clearTimeout(hazardTooltipTimer);hazardTooltipTimer=null;}$('hazard-tooltip').hidden=true;if(!trafficSelected)$('traffic-tooltip').hidden=true;});
document.addEventListener('pointermove',()=>{notePointerActivity();if(aloftWorker)aloftWorker.postMessage({type:'pointer'});else aloftPointerQuietUntil=performance.now()+150;},{passive:true});
function endMapPointer(event){activePointers.delete(event.pointerId);if(pinch&&activePointers.size>=2){startPinch();return;}if(pinch&&activePointers.size===1){const [pointerId,point]=activePointers.entries().next().value;pinch=null;drag={pointerId,x:point[0],y:point[1],pan:[...pan]};return;}pinch=null;if(drag?.pointerId===event.pointerId)drag=null;if(!activePointers.size)map.classList.remove('dragging');}
for(const type of ['pointerup','pointercancel'])map.addEventListener(type,endMapPointer);
map.addEventListener('wheel',e=>{e.preventDefault();changeZoom(e.deltaY<0?1.1:1/1.1,mapPoint(e));},{passive:false});
new ResizeObserver(()=>{if(stations.length){draw();updateMarkers();}}).observe(map);
async function initialize(){try{
 const results=await Promise.all(['stations.json?v=20260920-kcdk-no-fuel1','states.json?v=regional1','airspaces.json?v=restricted1'].map(async url=>{const r=await fetch(url);if(!r.ok)throw Error('Map asset unavailable');return r.json();}));
 states=results[1].features;establishedRegion=makeRegionFilter(states);stations=results[0].filter(station=>establishedRegion.containsPoint(station.lon,station.lat)).sort((a,b)=>a.priority-b.priority||a.id.localeCompare(b.id));airspaces=filterFeatureGroups(results[2].features,establishedRegion,feature=>feature.properties?.id);
 createMarkers();draw();updateMarkers();await refresh();select('KLKR');
 updateTerrain();
 loadWater();
 updateRadar();
 loadFronts();
 loadWindsAloft();
 loadHazards(false,true);loadTfrs(false,true);
}catch(error){console.error(error);notify('Unable to load the map. Reload the page to try again.',true);}
updateClock();setInterval(()=>{updateMarkers();updateClock();if(frontsOn&&!frontDataCurrent())drawFronts();},30000);setInterval(updateRadar,300000);setInterval(updateLightning,300000);setInterval(loadFronts,900000);setInterval(()=>loadWindsAloft(true),1800000);
setInterval(()=>loadHazards(true,true),300000);setInterval(()=>loadTfrs(true,true),300000);
document.addEventListener('visibilitychange',()=>{if(document.hidden){clearTimeout(trafficTimer);trafficTimer=null;if(aloftWorker)aloftWorker.postMessage({type:'enabled',enabled:false});else if(aloftAnimation){cancelAnimationFrame(aloftAnimation);aloftAnimation=null;}}else{updateMarkers();refresh();updateTerrain();loadWater();updateRadar();updateLightning();loadFronts();loadWindsAloft(true);startAloftAnimation();loadHazards(true,true);loadTfrs(true,true);loadTraffic();}});}
initialize();
