#!/usr/bin/env python3
import json, pathlib, re

ROOT = pathlib.Path(__file__).resolve().parents[1]
META = ROOT / 'photo_metadata.json'

if not META.exists():
    raise SystemExit('photo_metadata.json not found')

data = json.loads(META.read_text(encoding='utf-8'))
audio_paths = {str(x.get('path') or '').replace('\\','/') for x in data if x.get('media_type') == 'audio'}
if not audio_paths:
    print('No audio archive records to render')
    raise SystemExit(0)

pages = [ROOT/'gallery.html'] + sorted(ROOT.glob('*-photos.html'))
changed = 0
players = 0

for page in pages:
    if not page.exists():
        continue
    text = page.read_text(encoding='utf-8')
    original = text

    if '.archive-audio-wrap{' not in text:
        css = '.archive-audio-wrap{position:relative;background:#f2f2f2;padding:48px 12px 16px}.archive-audio-wrap audio{width:100%;display:block}.archive-audio-label{position:absolute;left:9px;top:9px;background:#222;color:#fff;padding:4px 7px;border-radius:5px;font-size:.78rem}'
        text = text.replace('</style>', css + '\n</style>', 1)

    for path in sorted(audio_paths):
        ep = re.escape(path)
        # Replace the image/viewer media block generated by the normal gallery builder.
        pattern = re.compile(r'<button class="archive-pic" data-view-i="(?P<i>\d+)"><img src="' + ep + r'"[^>]*></button>')
        repl = '<div class="archive-audio-wrap"><div class="archive-audio-label">Audio</div><audio controls preload="metadata" src="' + path + '">Your browser does not support this audio file.</audio></div>'
        text, n = pattern.subn(repl, text)
        players += n

        # Audio does not use the image popup; replace its actions with a direct download.
        article_pattern = re.compile(
            r'(<article class="archive-card" data-i="\d+">.*?<audio controls preload="metadata" src="' + ep + r'".*?</audio>.*?<div class="archive-file">.*?</div>)'
            r'<div class="archive-actions"><button data-view-i="\d+">View</button><a href="' + ep + r'" download>Download high resolution</a></div>',
            re.S
        )
        text = article_pattern.sub(r'\1<div class="archive-actions"><a href="' + path + r'" download>Download audio</a></div>', text)

    if text != original:
        page.write_text(text, encoding='utf-8')
        changed += 1

print(f'Audio player post-process: {players} player cards across {changed} pages')
