param([string]$TestRoot='website-test-v38')
$ErrorActionPreference='Stop'
$RepoRoot=Split-Path -Parent $PSScriptRoot
$Root=Join-Path $RepoRoot $TestRoot
$ThumbRoot=Join-Path $Root 'thumbs'
$ViewRoot=Join-Path $Root 'images'
$OriginalRoot=Join-Path $Root 'originals'
$MetadataPath=Join-Path $RepoRoot 'photo_metadata.json'
$Output=Join-Path $Root 'gallery-chronological-test.html'
foreach($p in @($ThumbRoot,$ViewRoot,$OriginalRoot,$MetadataPath)){if(!(Test-Path -LiteralPath $p)){throw "Missing: $p"}}
function HtmlEncode([string]$s){[System.Net.WebUtility]::HtmlEncode([string]$s)}
function UrlPath([string]$s){$s-replace '\\','/'}
function FormatDate([string]$v){if(!$v){return ''};if($v-match'^(\d{4})-(\d{2})-(\d{2})'){$y=[int]$Matches[1];$m=[int]$Matches[2];$d=[int]$Matches[3];if($m-eq 1-and$d-eq 1){return "$y"};$mn=[Globalization.CultureInfo]::GetCultureInfo('en-US').DateTimeFormat.GetMonthName($m);if($d-eq 1){return "$mn $y"};return "$mn $d, $y"};return $v}
function SortKey($m,[string]$name){$d=if($m){[string]$m.date}else{''};if($d-match'^(\d{4})-(\d{2})-(\d{2})'){return ('{0:D4}{1:D2}{2:D2}|{3}'-f [int]$Matches[1],[int]$Matches[2],[int]$Matches[3],$name.ToLower())};if($d-match'^\d{4}$'){return "$d`0101|$($name.ToLower())"};return "99999999|$($name.ToLower())"}
function PeopleDisplay($vals){if(!$vals){return ''};(($vals|ForEach-Object{([string]$_)-replace'(?i)\s+Bell$',' B'})-join', ')}
$abbr=@{'South Carolina'='SC';'North Carolina'='NC';'Florida'='FL';'Georgia'='GA';'Virginia'='VA';'Tennessee'='TN';'New York'='NY';'Pennsylvania'='PA';'Maryland'='MD';'Alabama'='AL';'Mississippi'='MS';'Texas'='TX';'California'='CA';'Ohio'='OH';'West Virginia'='WV'}
function LocationDisplay($m){if(!$m){return ''};$loc=[string]$m.location;$city=[string]$m.city;$state=[string]$m.state;if($loc -match'(?i)^Mason St Orig Bell Family Home$'){$loc='Mason St'};if($abbr.ContainsKey($state)){$state=$abbr[$state]};(@($loc,$city,$state)|Where-Object{![string]::IsNullOrWhiteSpace($_)})-join', '}
$meta=Get-Content -LiteralPath $MetadataPath -Raw|ConvertFrom-Json
$by=@{};foreach($m in $meta){if($m.path){$by[([string]$m.path).ToLower()]=$m}}
$rows=@();$exts=@('.jpg','.jpeg','.png','.tif','.tiff','.webp')
foreach($t in Get-ChildItem -LiteralPath $ThumbRoot -File -Recurse|Where-Object{$exts-contains$_.Extension.ToLower()}){$rel=$t.FullName.Substring($ThumbRoot.Length).TrimStart('\','/');$key=('images/'+(UrlPath $rel)).ToLower();$m=$by[$key];$rows+=[pscustomobject]@{Rel=$rel;Meta=$m;Key=(SortKey $m $t.Name)}}
$rows=$rows|Sort-Object Key
$cards=New-Object Collections.Generic.List[string];$items=New-Object Collections.Generic.List[string];$i=0
foreach($r in $rows){$rel=$r.Rel;$m=$r.Meta;$name=[IO.Path]::GetFileName($rel);$title=if($m -and $m.title){[string]$m.title}else{$name};$date=if($m){FormatDate ([string]$m.date)}else{''};$loc=LocationDisplay $m;$people=if($m){PeopleDisplay $m.people}else{''};$desc=if($m){[string]$m.description}else{''};$thumb='thumbs/'+(UrlPath $rel);$view='images/'+(UrlPath $rel);$orig='originals/'+(UrlPath $rel);$cards.Add("<article class='card'><button class='pic' data-i='$i'><img src='$(HtmlEncode $thumb)' loading='lazy'></button><div class='copy'><h3>$(HtmlEncode $title)</h3>$(if($date){"<div class='meta'>$(HtmlEncode $date)</div>"})$(if($loc){"<div class='meta'>$(HtmlEncode $loc)</div>"})$(if($people){"<div class='meta'>$(HtmlEncode $people)</div>"})$(if($desc){"<p>$(HtmlEncode $desc)</p>"})<div class='file'>$(HtmlEncode $name)</div><div class='actions'><button data-i='$i'>View</button><a href='$(HtmlEncode $orig)' download>Download full resolution</a></div></div></article>");$items.Add((([ordered]@{view=$view;orig=$orig;title=$title;date=$date;location=$loc;people=$people;description=$desc;name=$name})|ConvertTo-Json -Compress));$i++}
$html=@"
<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Chronological Gallery Test</title><style>body{font-family:Segoe UI,Arial,sans-serif;margin:0;background:#f5f5f5}.main{max-width:1500px;margin:auto;padding:28px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));gap:18px}.card{background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 2px 10px #0002}.pic{width:100%;border:0;padding:0;background:#eee}.pic img{width:100%;height:230px;object-fit:contain;display:block}.copy{padding:12px}.copy h3{margin:0 0 7px}.meta{font-size:.9rem;line-height:1.45;color:#555}.copy p{white-space:pre-line}.file{font-size:.78rem;color:#888;margin-top:8px}.actions{display:flex;gap:12px;margin-top:9px}.actions button{border:0;background:none;color:#06c;text-decoration:underline;padding:0}.modal{position:fixed;inset:0;background:#000e;display:none;align-items:center;justify-content:center;z-index:10}.modal.open{display:flex}.inner{width:96vw;height:94vh;display:grid;grid-template-rows:1fr auto}.stage{position:relative;display:flex;align-items:center;justify-content:center}.stage img{max-width:100%;max-height:100%;object-fit:contain}.nav,.close{position:absolute;border:0;border-radius:50%;background:#0008;color:#fff}.nav{top:50%;transform:translateY(-50%);font-size:40px;width:56px;height:56px}.prev{left:12px}.next{right:12px}.close{right:12px;top:12px;font-size:28px;width:46px;height:46px}.info{color:#fff;text-align:center;padding:8px}.line{margin:2px 0}</style></head><body><main class='main'><h1>Chronological Gallery Test</h1><p>Oldest first. Date, location, and people are displayed on separate lines.</p><div class='grid'>$($cards -join "`n")</div></main><div class='modal' id='m'><div class='inner'><div class='stage'><img id='mi'><button class='nav prev' id='p'>&#10094;</button><button class='nav next' id='n'>&#10095;</button><button class='close' id='c'>&times;</button></div><div class='info'><h3 id='mt'></h3><div class='line' id='md'></div><div class='line' id='ml'></div><div class='line' id='mp'></div><div class='line' id='mc'></div></div></div></div><script>const x=[$($items -join ',')];let k=0;const m=document.getElementById('m');function show(i){k=(i+x.length)%x.length;const a=x[k];mi.src=a.view;mt.textContent=a.title;md.textContent=a.date||'';ml.textContent=a.location||'';mp.textContent=a.people||'';mc.textContent=a.description||'';m.classList.add('open')}document.querySelectorAll('[data-i]').forEach(e=>e.onclick=()=>show(+e.dataset.i));p.onclick=()=>show(k-1);n.onclick=()=>show(k+1);c.onclick=()=>m.classList.remove('open');document.onkeydown=e=>{if(!m.classList.contains('open'))return;if(e.key==='ArrowLeft')show(k-1);if(e.key==='ArrowRight')show(k+1);if(e.key==='Escape')m.classList.remove('open')}</script></body></html>
"@
[IO.File]::WriteAllText($Output,$html,[Text.UTF8Encoding]::new($false))
Write-Host "Created: $Output"
Write-Host "Cards:   $($rows.Count)"
Write-Host "Order:   chronological ascending (unknown dates last)"
